name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'tutorials/**'
      - 'src/**'
      - 'Project.toml'
      - 'Manifest.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'tutorials/**'
      - 'src/**'
      - 'Project.toml'
      - 'Manifest.toml'

  workflow_dispatch: # Allows running workflow manually from the Actions tab

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.7'

      - name: Cache artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'

      # include this at a later time
      #- run: |
      #    julia --project=docs -e '
      #      using Documenter: DocMeta, doctest
      #      using Conductor
      #      DocMeta.setdocmeta!(Conductor, :DocTestSetup, :(using Conductor); recursive=true)
      #      doctest(Conductor)'

      - name: Build and Deploy Docs
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
